[build]
  functions = "netlify/functions"

[[redirects]]
  from = "/upload"
  to = "/.netlify/functions/upload"
  status = 200

[[redirects]]
  from = "/latest"
  to = "/.netlify/functions/latest"
  status = 200
