name = "image-to-qr-api"
main = "src/index.js"
compatibility_date = "2024-12-17"

# R2 Bucket binding
[[r2_buckets]]
binding = "UPLOADS_BUCKET"
bucket_name = "image-uploads"
preview_bucket_name = "image-uploads-preview"
